/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ExtractedData } from "./ExtractedData";
import { ExtractedDataCountArgs } from "./ExtractedDataCountArgs";
import { ExtractedDataFindManyArgs } from "./ExtractedDataFindManyArgs";
import { ExtractedDataFindUniqueArgs } from "./ExtractedDataFindUniqueArgs";
import { DeleteExtractedDataArgs } from "./DeleteExtractedDataArgs";
import { ExtractedDataService } from "../extractedData.service";
@graphql.Resolver(() => ExtractedData)
export class ExtractedDataResolverBase {
  constructor(protected readonly service: ExtractedDataService) {}

  async _extractedDataItemsMeta(
    @graphql.Args() args: ExtractedDataCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ExtractedData])
  async extractedDataItems(
    @graphql.Args() args: ExtractedDataFindManyArgs
  ): Promise<ExtractedData[]> {
    return this.service.extractedDataItems(args);
  }

  @graphql.Query(() => ExtractedData, { nullable: true })
  async extractedData(
    @graphql.Args() args: ExtractedDataFindUniqueArgs
  ): Promise<ExtractedData | null> {
    const result = await this.service.extractedData(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ExtractedData)
  async deleteExtractedData(
    @graphql.Args() args: DeleteExtractedDataArgs
  ): Promise<ExtractedData | null> {
    try {
      return await this.service.deleteExtractedData(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
